version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    branches:
      only:
        - develop
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - run:
          name: install-rsync
          command: sudo yum install rsync
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install node_modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: 'build (create `dist` directory)'
          command: npm run build
      - run:
          name: deploy to master
          command: |
            set -e
            DEPLOY_DIR=deploy
            git config --global push.default simple
            git config --global user.email $(git --no-pager show -s --format='%ae' HEAD)
            git config --global user.name $CIRCLE_USERNAME
            git clone -q --branch=master $CIRCLE_REPOSITORY_URL $DEPLOY_DIR
            cd $DEPLOY_DIR
            rsync -arv --delete ../dist/* .
            git add -f .
            git commit -m "Deploy build $CIRCLE_BUILD_NUM [ci skip]" || true
            git push -f
